# Jekyll configuration
markdown: redcarpet
permalink: posts/:title
baseurl:

# feed.atom configuration
name: Fundacion Francisco de Miranda
url: http://galerialibertadchile.cl
description: "Somos una organización sin fines de lucro que busca rescatar el patrimonio histórico y cultural de Chile y América Latina."
author: Fundacion Miranda
keywords: "francisco de miranda, sudamerica, monumento, biblioteca, miguel castillo didier, america, america latina, latinoamerica, independencia, cultura, historia, bernaro ohiggins"

disqus:
  shortname: fundacionfranciscodemiranda

twitter:
  username: '@FundacionMiranda'

google:
  analytics: 'UA-12345678-9'

collections:
  documents:
    output: true
  flyers:
    output: true
  presentations:
    output: true
